import "./globals.css";
import { Roboto} from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
});

// const gothic = Gothic_A1({
//   subsets: ['latin'],
//   weight: '400',
//   variable: '--font-gothic',
// });

export const metadata = {
  title: "muhmmmad m. | mern stack developer | frontend developer | backend developer | deployment specialist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <head>
        <title>My Portfolio</title>
         <link rel="icon" type="image/x-icon" href="/electronics.png" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
